### ISSUE TITLE
First task (coding group)

### ISSUE THREAD

**Issue by amrsamii** [amrsamii/ASUMobilCarG31#1]
we are to learn uart , ultrasonic , sevro , pwm to control motors speed for avr and simulate simple project after learning them 

mohammed refaat : learn servo motor
eslam tarek : ultrasonic , pwm
amr samy : uart ,pwm
after learning it's required to upload our project with the simulation

we have 10 days to finish this task
good luck

sources
simply avr available just download it
this playlist https://www.youtube.com/playlist?list=PLE72E4CFE73BD1DE1

**Comment by Solariii** [comment]
Tmam

**Comment by mohamedrefaaat** [comment]
tmam
